---
- name: Install and Configure Kerberos
  hosts: krb5server, krb5client
  become: true
  vars:
    kerberos_user: "kerberos"

  tasks:
    - name: Install krb5-kdc and krb5-admin-server
      apt:
        update_cache: true
        name: ["krb5-kdc", "krb5-admin-server"]
        state: present
      when:
        - inventory_hostname in groups["krb5server"]

    - name: Configure kdc.conf
      template:
        src: kdc.conf.j2
        dest: /etc/krb5kdc/kdc.conf
      when:
        - inventory_hostname in groups["krb5server"]
      tags:
        - configuration
      become: true

    - name: Configure krb5.conf
      template:
        src: krb5.conf.j2
        dest: /etc/krb5.conf
      tags:
        - configuration

    - name: Configure kadm5.acl
      template:
        src: kadm5.acl.j2
        dest: /etc/krb5kdc/kadm5.acl
      when:
        - inventory_hostname in groups["krb5server"]
      tags:
        - configuration

    - name: Create kdc database for KAHOVEC.DEV
      shell: kdb5_util create -r ATHENA.MIT.EDU -s
      become: true
      run_once: true
      when:
        - inventory_hostname in groups["krb5server"]
      tags:
        - configuration

    - name: Install krb-user
      apt:
        update_cache: true
        name: krb5-user
        state: present
      when:
        - inventory_hostname in groups["krb5client"]
