- name: Add Kerberos principal
  ansible.builtin.expect:
    command: kadmin.local -q "addprinc {{ primary }}/{{ instance }}@KAHOVEC.DEV -pw {{ password }}"
  become: yes
  register: result
  run_once: true

- name: Print output
  debug:
    var: result.stdout_lines
