- name: Ensure Keytab Directory exists
  ansible.builtin.file:
    path: "{{ path }}"
    state: directory

- name: Generate keytab
  become: true
  shell: |
    kadmin.local -q "ktadd -norandkey -k {{ path }}/{{ name }} {{ principal }}"
  register: keytab_output
