---
- name: Install and Configure Hadoop
  hosts: namenodes, workernodes
  become: true
  vars:
    hadoop_user: "hadoop"
    hadoop_version: "3.3.6"  # Change this to the desired Hadoop version
    java_package: "openjdk-8-jdk"  # Change this if you prefer a different Java version
    hadoop_tarball_local_path: "files/common/hadoop-{{ hadoop_version }}.tar.gz"  # Change this to your local path

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install Java
      apt:
        name: "{{ java_package }}"
        state: present

    - name: Copy Hadoop tarball to remote hosts
      ansible.builtin.copy:
        src: "{{ hadoop_tarball_local_path }}"
        dest: "/tmp/hadoop-{{ hadoop_version }}.tar.gz"

    - name: Extract Hadoop tarball
      ansible.builtin.unarchive:
        src: "/tmp/hadoop-{{ hadoop_version }}.tar.gz"
        dest: "/opt/"
        owner: "{{ hadoop_user }}"
        group: "{{ hadoop_user }}"
        remote_src: yes

    - name: Create a symbolic link
      ansible.builtin.file:
        src: /opt/hadoop-{{ hadoop_version }}
        dest: /opt/hadoop
        owner: "{{ hadoop_user }}"
        group: "{{ hadoop_user }}"
        state: link

    - name: Create Data Directory
      ansible.builtin.file:
        path: /srv/hadoop/hdfs/data
        owner: "{{ hadoop_user }}"
        group: "{{ hadoop_user }}"
        state: directory
        mode: '0755'

    - name: Create NameNode Directory
      ansible.builtin.file:
        path: /srv/hadoop/hdfs/name
        owner: "{{ hadoop_user }}"
        group: "{{ hadoop_user }}"
        state: directory
        mode: '0755'

    - name: Set Hadoop environment variables
      lineinfile:
        path: /etc/environment
        line: 'export HADOOP_HOME=/opt/hadoop'
      become: true

    - name: Add Hadoop to PATH for all Users
      copy:
        content: "export PATH=$PATH:$HADOOP_HOME/bin"
        dest: "/etc/profile.d/hadoop_path.sh"
      become: true

    - name: Set JAVA_HOME in hadoop-env.sh User
      lineinfile:
        path: /opt/hadoop/etc/hadoop/hadoop-env.sh
        search_string: '# export JAVA_HOME='
        line: 'export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64'


    - name: Configure Hadoop core-site.xml
      template:
        src: templates/core-site.xml.j2
        dest: /opt/hadoop/etc/hadoop/core-site.xml
        owner: "{{ hadoop_user }}"
        group: "{{ hadoop_user }}"
      tags:
         - configuration

    - name: Configure Hadoop hdfs-site.xml
      template:
        src: templates/hdfs-site.xml.j2
        dest: /opt/hadoop/etc/hadoop/hdfs-site.xml
        owner: "{{ hadoop_user }}"
        group: "{{ hadoop_user }}"
      tags:
         - configuration

    - name: Configure Yarn yarn-site.xml
      template:
        src: templates/yarn-site.xml.j2
        dest: /opt/hadoop/etc/hadoop/yarn-site.xml
        owner: "{{ hadoop_user }}"
        group: "{{ hadoop_user }}"
      tags:
         - configuration

    - name: Configure Hadoop mapred-site.xml
      template:
        src: templates/mapred-site.xml.j2
        dest: /opt/hadoop/etc/hadoop/mapred-site.xml
        owner: "{{ hadoop_user }}"
        group: "{{ hadoop_user }}"
      tags:
         - configuration

    - name: Configure systemd datanode service
      template:
        src: templates/hadoop-datanode.service.j2
        dest: /etc/systemd/system/hadoop-datanode.service
      tags:
         - configuration
      become: true

    - name: Configure systemd namenode service
      template:
        src: templates/hadoop-namenode.service.j2
        dest: /etc/systemd/system/hadoop-namenode.service
      tags:
         - configuration
      become: true

    - name: Configure systemd resourcemanager service
      template:
        src: templates/yarn-resourcemanager.service.j2
        dest: /etc/systemd/system/yarn-resourcemanager.service
      tags:
         - configuration
      become: true

    - name: Configure systemd nodemanager service
      template:
        src: templates/yarn-nodemanager.service.j2
        dest: /etc/systemd/system/yarn-nodemanager.service
      tags:
         - configuration
      become: true

    - name: Enable namenode service
      ansible.builtin.systemd_service:
        name: hadoop-namenode
        enabled: true
      tags:
         - configuration
      when:
        - inventory_hostname in groups["namenodes"]

    - name: Enable datanode service
      ansible.builtin.systemd_service:
        name: hadoop-datanode
        enabled: true
      tags:
         - configuration
      when:
        - inventory_hostname in groups["workernodes"]

    - name: Enable resourcemanager service
      ansible.builtin.systemd_service:
        name: yarn-resourcemanager
        enabled: true
      tags:
         - configuration
      when:
        - inventory_hostname in groups["namenodes"]

    - name: Enable nodemanager service
      ansible.builtin.systemd_service:
        name: yarn-nodemanager
        enabled: true
      tags:
         - configuration
      when:
        - inventory_hostname in groups["workernodes"]

    - name: Add hosts to HADOOP_HOME/etc/hadoop/workers
      lineinfile:
        dest: "/opt/hadoop/etc/hadoop/workers"
        line: "{{ item }}"
      loop: "{{ groups['workernodes'] }}"
