---
- name: Install and Configure Hadoop
  hosts: controllers
  become: true
  vars:
    hadoop_user: "hadoop"
    hadoop_version: "3.3.6"  # Change this to the desired Hadoop version
    java_package: "openjdk-8-jdk"  # Change this if you prefer a different Java version
    hadoop_tarball_local_path: "files/common/hadoop-{{ hadoop_version }}.tar.gz"  # Change this to your local path

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install Java
      apt:
        name: "{{ java_package }}"
        state: present

    - name: Copy Hadoop tarball to remote hosts
      ansible.builtin.copy:
        src: "{{ hadoop_tarball_local_path }}"
        dest: "/tmp/hadoop-{{ hadoop_version }}.tar.gz"

    - name: Extract Hadoop tarball
      ansible.builtin.unarchive:
        src: "/tmp/hadoop-{{ hadoop_version }}.tar.gz"
        dest: "/opt/"
        owner: "{{ hadoop_user }}"
        group: "{{ hadoop_user }}"
        remote_src: yes

    - name: Create a symbolic link
      ansible.builtin.file:
        src: /opt/hadoop-{{ hadoop_version }}
        dest: /opt/hadoop
        owner: "{{ hadoop_user }}"
        group: "{{ hadoop_user }}"
        state: link

    - name: Set Hadoop environment variables
      lineinfile:
        path: /etc/environment
        line: 'export HADOOP_HOME=/opt/hadoop'
      become: true

    - name: Add Hadoop to PATH
      lineinfile:
        path: /etc/environment
        line: 'export HADOOP_HOME=/opt/hadoop'
      become: true

    - name: Check if HADOOP_HOME/bin is in PATH
      command: echo $PATH
      register: current_path
      changed_when: false
      failed_when: false

    - name: Add HADOOP_HOME/bin to PATH if not present
      lineinfile:
        path: "/home/{{ hadoop_user }}/.bashrc"
        line: "export PATH=$PATH:$HADOOP_HOME/bin"
        insertafter: EOF
      when: "'$HADOOP_HOME' not in current_path.stdout"

    - name: Configure Hadoop core-site.xml
      template:
        src: templates/core-site.xml.j2
        dest: /opt/hadoop/etc/hadoop/core-site.xml
        owner: "{{ hadoop_user }}"
        group: "{{ hadoop_user }}"
      # notify: Restart Hadoop

    - name: Configure Hadoop hdfs-site.xml
      template:
        src: templates/hdfs-site.xml.j2
        dest: /opt/hadoop/etc/hadoop/hdfs-site.xml
        owner: "{{ hadoop_user }}"
        group: "{{ hadoop_user }}"
  #     notify: Restart Hadoop

  #   # Add additional configuration tasks for other Hadoop components (e.g., mapred-site.xml, yarn-site.xml)

  # handlers:
  #   - name: Restart Hadoop
  #     command: "{{ hadoop_home }}/sbin/stop-all.sh && {{ hadoop_home }}/sbin/start-all.sh"
