---
- name: Create Linux User
  hosts: controllers, workernodes
  become: yes

  vars:
    new_username: spark

  tasks:
    - name: Add the user '{{ new_username }}'
      ansible.builtin.user:
        name: '{{ new_username }}'
        shell: /bin/bash
        create_home: true