- name: Setup Linux
  tags:
    - linux
  hosts: controllers, workernodes
  gather_facts: yes
  become: true
  tasks:
    - name: Create User
      loop: "{{ users }}"
      vars:
        new_user: "{{ item.name }}"
        new_user_group: "{{ item.group }}"
      ansible.builtin.include_tasks:
        file: tasks/linux/create-user.yml
    - name: Install required packages
      ansible.builtin.include_tasks:
        file: tasks/linux/install-packages.yml
    - name: Generate /etc/hosts
      ansible.builtin.include_tasks:
        file: tasks/linux/generate-hosts-file.yml

- name: Setup Kerberos
  tags:
    - kerberos
  hosts: krb5server, krb5client
  become: true
  tasks:
    - name: Install Kerberos
      ansible.builtin.include_tasks:
        file: tasks/kerberos/install.yml
    - name: Create Database
      ansible.builtin.include_tasks:
        file: tasks/kerberos/create_db.yml
      when:
        - inventory_hostname in groups["krb5server"]
    - name: Start Daemons
      ansible.builtin.include_tasks:
        file: tasks/kerberos/start_daemons.yml
      when:
        - inventory_hostname in groups["krb5server"]

- name: Kerberize Hadoop
  tags:
    - kerberize
  hosts: controllers, workernodes
  become: true
  vars:
    hosts: "{{ groups['all'] | unique }}"
  tasks:
    - name: Add Kerberos Principal
      loop: "{{ hosts | product(services) | list }}"
      vars:
        primary: "{{ item[1].name }}"
        instance: "{{ item[0] }}"
        realm: "{{ kerberos.realm }}"
        password: "{{ kerberos.password }}" # FIXME: use ansible vault
      ansible.builtin.include_tasks:
        file: tasks/kerberos/add_princ.yml
      when:
        - inventory_hostname in groups["controllers"]
    - name: Create temporary Keytab on Kerberos Admin Server
      loop: "{{ hosts | product(services) | list }}"
      vars:
        path: "/tmp/keytabs/{{ item[0] }}"
        name: "{{ item[1].name }}.service.keytab"
        principal: "{{ item[1].name }}/{{ item[0] }}@{{ kerberos.realm }} host/{{ item[0] }}@{{ kerberos.realm }}"
      ansible.builtin.include_tasks:
        file: tasks/kerberos/create_keytab.yml
      when:
        - inventory_hostname in groups["controllers"]
    - name: Copy temporary Keytab to local
      ansible.posix.synchronize:
        src: /tmp/keytabs/
        dest: /tmp/ansible_keytabs
        owner: true
        group: true
        mode: pull
      when:
        - inventory_hostname in groups["controllers"]
    - name: Delete existing Keytab
      ansible.builtin.file:
        path: "{{ kerberos.keytab_path }}"
        state: absent
    - name: Distribute Keytab
      ansible.posix.synchronize:
        src: /tmp/ansible_keytabs/{{ inventory_hostname }}/
        dest: "{{ kerberos.keytab_path }}"
        mode: push
    - name: Remove Tempory Keytab Dir on Kerberos Admin Server
      ansible.builtin.file:
        path: /tmp/ansible_keytabs/
        state: absent
      when:
        - inventory_hostname in groups["controllers"]
    - name: Change file ownership, group and permissions
      loop: "{{ services }}"
      ansible.builtin.file:
        path: /etc/security/keytab/{{ item.name }}.service.keytab
        owner: "{{ item.user }}"
        group: "{{ users.hadoop.group }}"
        mode: "0400"

- name: Remove Temporary Keytabs locally
  hosts: 127.0.0.1
  connection: local
  tags: kerberize
  tasks:
    - name: Delete local directory
      file: path=/tmp/ansible_keytabs/ state=absent

- name: Setup Hadoop
  tags:
    - hadoop
  hosts: controllers, workernodes
  become: true
  vars:
    hadoop_user: "hadoop"
    hdfs_user: "hdfs"
    yarn_user: "yarn"
    mapred_user: "mapred"
    hadoop_group: "hadoop"
    hadoop_version: "3.3.6"
    filename: "hadoop-{{ hadoop_version }}.tar.gz"
  tasks:
    - name: Distribute Certs
      ansible.builtin.include_tasks:
        file: tasks/hadoop/distribute_cert.yml
    - name: Kinit
      become: true
      shell: kinit -k -t /etc/security/keytab/dn.service.keytab dn/vm-controller@KAHOVEC.DEV
      register: keytab_output
      when:
        - inventory_hostname in groups["controllers"]
    - name: Install Hadoop
      ansible.builtin.include_tasks:
        file: tasks/hadoop/install.yml
    - name: Configure Hadoop
      ansible.builtin.include_tasks:
        file: tasks/hadoop/configure.yml

- name: Setup MySQL
  hosts: controllers
  tags:
    - mysql
  become: true
  tasks:
    - name: Install MySQL
      ansible.builtin.include_tasks:
        file: tasks/mysql/install.yml

- name: Setup Hive
  tags:
    - hive
  hosts: controllers
  become: true
  vars:
    hive_user: "hive"
    hive_group: "hadoop"
    hive_version: "4.0.0"
    filename: "apache-hive-{{ hive_version }}-bin.tar.gz"
    jdbc_file: "mysql-connector-j-8.4.0.jar"
  tasks:
    - name: Create MySQL User
      vars:
        user: "{{ hive_user }}"
        password: "Sup3rS3cur3Pa55w0rd!"
        db: "hive_metastore"
        table: "*"
        privileges: "ALL"
      ansible.builtin.include_tasks:
        file: tasks/mysql/create-user.yml
    - name: Kinit
      become: true
      shell: kinit -k -t /etc/security/keytab/dn.service.keytab dn/vm-controller@KAHOVEC.DEV
      register: keytab_output
    - name: Install Hive
      ansible.builtin.include_tasks:
        file: tasks/hive/install.yml
    - name: Configure Hive
      ansible.builtin.include_tasks:
        file: tasks/hive/configure.yml

- name: Setup Kafka
  tags:
    - kafka
  hosts: controllers, workernodes
  become: true
  vars:
    kafka_user: "kafka"
    kafka_group: "hadoop"
    kafka_version: "2.12-3.7.0"
    filename: "kafka_{{ kafka_version }}.tgz"
  tasks:
    - name: Install Kafka
      ansible.builtin.include_tasks:
        file: tasks/kafka/install.yml

- name: Setup Spark
  tags:
    - spark
  hosts: controllers, workernodes
  become: true
  vars:
    spark_user: "spark"
    spark_group: "hadoop"
    spark_version: "3.5.1"
    filename: "spark-{{ spark_version }}-bin-hadoop3.tgz"
  tasks:
    - name: Install Spark
      ansible.builtin.include_tasks:
        file: tasks/spark/install.yml
