---
- name: Start Standalone Spark Cluster
  hosts: controllers, workernodes
  become: true
  become_user: spark

  tasks:
    - name: Check SPARK_HOME
      shell: echo $SPARK_HOME
      register: spark_home
      failed_when: spark_home.stdout == ""

    - name: Start Spark Master
      command: "$SPARK_HOME/sbin/start-master.sh"
      when:
        - inventory_hostname in groups["controllers"]

    - name: Start Spark Worker
      command: "$SPARK_HOME/sbin/start-worker.sh spark://{{ groups['controllers'][0] }}:7077"
      when:
        - inventory_hostname in groups["workernodes"]
    
