- name: Start Cluster
  hosts: controllers, workernodes
  become: true

  tasks:
    - name: Start Hadoop Services
      ansible.builtin.include_tasks:
        file: tasks/hadoop/start-services.yml
    - name: Start Hive Services
      ansible.builtin.include_tasks:
        file: tasks/hive/start-services.yml
      when:
        - inventory_hostname in groups["controllers"]
    - name: Start Kafka Services
      ansible.builtin.include_tasks:
        file: tasks/kafka/start-services.yml
    - name: Start Spark Services
      ansible.builtin.include_tasks:
        file: tasks/spark/start-standalone-services.yml
