- name: Start Hadoop
  tags:
    - hadoop
  hosts: controllers, workernodes
  become: true

  tasks:
    - name: Start Hadoop Services
      ansible.builtin.include_tasks:
        file: tasks/hadoop/start_services.yml
      vars:
        service: "all"

- name: Start Hive
  tags:
    - hive
  hosts: controllers, workernodes
  become: true

  tasks:
    - name: Start Hive Services
      ansible.builtin.include_tasks:
        file: tasks/hive/start_services.yml
      vars:
        service: "all"

- name: Start Spark
  tags:
    - spark
  hosts: controllers, workernodes
  become: true

  tasks:
    - name: Start Spark Services
      ansible.builtin.include_tasks:
        file: tasks/spark/start_standalone_services.yml
      vars:
        service: "all"

- name: Start Kafka
  tags:
    - kafka
  hosts: controllers, workernodes
  become: true

  tasks:
    - name: Start Kafka
      ansible.builtin.include_tasks:
        file: tasks/kafka/start_services.yml
      vars:
        service: "all"
