- name: Stop Hadoop
  tags:
    - hadoop
  hosts: controllers, workernodes
  become: true

  tasks:
    - name: Start Hadoop Services

      ansible.builtin.include_tasks:
        file: tasks/hadoop/stop_services.yml
      vars:
        - service: "all"
