---
- name: Start Hive Services
  hosts: controllers
  become: true

  tasks:
    - name: Start Hive Metastore Service
      ansible.builtin.service:
        name: hive-metastore.service
        state: restarted

    - name: Start Hive Server2 Service
      ansible.builtin.service:
        name: hive-server2.service
        state: restarted
