all:
  vars:
    ansible_user: ansible
    kafka_cluster_id: 2BKCbwzCTxyCNEM8XkkU1A
  children:
    cluster:
      children:
        controllers:
          hosts:
            controller:
              kafka_node_id: 1

        namenodes:
          hosts:
            namenode:

        workernodes:
          hosts:
            worker01:
              kafka_node_id: 2
            worker02:
              kafka_node_id: 3            
