all:
  vars:
    ansible_user: ansible
    kafka_cluster_id: 2BKCbwzCTxyCNEM8XkkU1A
    java_package: "openjdk-8-jdk"
    java_home_path: "/usr/lib/jvm/java-1.8.0-openjdk-amd64"
    python_version: "3.10"
  children:
    cluster:
      children:
        controllers:
          hosts:
            vm-controller:
              kafka_node_id: 1

        namenodes:
          hosts:
            vm-controller:

        workernodes:
          hosts:
            vm-worker01:
              kafka_node_id: 2
            vm-worker02:
              kafka_node_id: 3
            vm-worker03:
              kafka_node_id: 4

        krb5server:
          hosts:
            vm-controller:

        krb5client:
          hosts:
            vm-worker01:
            vm-worker02:
            vm-worker03: