all:
  vars:
    ansible_user: ansible
  children:
    cluster:
      children:
        controllers:
          hosts:
            vm-controller:

        namenodes:
          hosts:
            vm-namenode:

        workers:
          hosts:
            vm-worker01:
            vm-worker02:
            vm-worker03:
