all:
  vars:
    ansible_user: ansible
    kafka_cluster_id: 2BKCbwzCTxyCNEM8XkkU1A
  children:
    cluster:
      children:
        controllers:
          hosts:
            vm-controller:
              kafka_node_id: 1

        namenodes:
          hosts:
            vm-namenode:

        workernodes:
          hosts:
            vm-worker01:
              kafka_node_id: 2
            vm-worker02:
              kafka_node_id: 3
            vm-worker03:
              kafka_node_id: 4

        krb5server:
          hosts:
            vm-controller:

        krb5client:
          hosts:
            vm-worker01:
            vm-worker02:
            vm-worker03: