- name: Ensure MySQL Service for Metastore is running
  ansible.builtin.systemd_service:
    name: mysql.service
    state: started
    enabled: true

- name: Copy Hive tarball to remote hosts
  ansible.builtin.copy:
    src: "{{ filename }}"
    dest: "/tmp/{{ filename }}"

- name: Remove existing Hive directory
  ansible.builtin.file:
    path: "/opt/apache-hive-{{ hive_version }}-bin"
    state: absent

- name: Extract Hive tarball
  ansible.builtin.unarchive:
    src: "/tmp/{{ filename }}"
    dest: "/opt/"
    owner: "{{ hive_user }}"
    group: "{{ hive_user }}"
    remote_src: yes

- name: Create a symbolic link
  ansible.builtin.file:
    src: /opt/apache-hive-{{ hive_version }}-bin
    dest: /opt/hive
    owner: "{{ hive_user }}"
    group: "{{ hive_user }}"
    state: link

- name: Set Hadoop environment variables
  lineinfile:
    path: /etc/environment
    line: "export HIVE_HOME=/opt/hive"
  become: true

- name: Add Hive to PATH for all Users
  lineinfile:
    path: /etc/bash.bashrc
    line: "export PATH=$PATH:$HIVE_HOME/bin"
  become: true

- name: Copy MySQL JDBC Driver
  ansible.builtin.copy:
    src: "{{ jdbc_file }}"
    dest: "/opt/hive/lib/{{ jdbc_file }}"
