#     ____           __        ____
#    /  _/___  _____/ /_____ _/ / /
#    / // __ \/ ___/ __/ __ `/ / /
#  _/ // / / (__  ) /_/ /_/ / / /
# /___/_/ /_/____/\__/\__,_/_/_/
#

- name: "Install Kerberos KDC"
  tags: ["kerberos_kdc", "kerberos_kdc_install"]
  ansible.builtin.import_tasks: "install.yml"

#    ______            _____
#   / ____/___  ____  / __(_)___ ___  __________
#  / /   / __ \/ __ \/ /_/ / __ `/ / / / ___/ _ \
# / /___/ /_/ / / / / __/ / /_/ / /_/ / /  /  __/
# \____/\____/_/ /_/_/ /_/\__, /\__,_/_/   \___/
#                        /____/
#

- name: "Confiure Kerberos KDC"
  tags: ["kerberos_kdc", "kerberos_kdc_configure"]
  ansible.builtin.import_tasks: "configure.yml"

#     ____            __                      ____        __        __
#    / __ \___  _____/ /__________  __  __   / __ \____ _/ /_____ _/ /_  ____ _________
#   / / / / _ \/ ___/ __/ ___/ __ \/ / / /  / / / / __ `/ __/ __ `/ __ \/ __ `/ ___/ _ \
#  / /_/ /  __(__  ) /_/ /  / /_/ / /_/ /  / /_/ / /_/ / /_/ /_/ / /_/ / /_/ (__  )  __/
# /_____/\___/____/\__/_/   \____/\__, /  /_____/\__,_/\__/\__,_/_.___/\__,_/____/\___/
#                                /____/

- name: "Destroy Database"
  tags: ["kerberos_kdc_destroy_database"]
  ansible.builtin.import_tasks: "destroy_db.yml"

#    ______                __          ____        __        __
#   / ____/_______  ____ _/ /____     / __ \____ _/ /_____ _/ /_  ____ _________
#  / /   / ___/ _ \/ __ `/ __/ _ \   / / / / __ `/ __/ __ `/ __ \/ __ `/ ___/ _ \
# / /___/ /  /  __/ /_/ / /_/  __/  / /_/ / /_/ / /_/ /_/ / /_/ / /_/ (__  )  __/
# \____/_/   \___/\__,_/\__/\___/  /_____/\__,_/\__/\__,_/_.___/\__,_/____/\___/
#

- name: "Create Database"
  tags: ["kerberos_kdc", "kerberos_kdc_create_database"]
  ansible.builtin.import_tasks: "create_db.yml"

#    _____ __             __     ____
#   / ___// /_____ ______/ /_   / __ \____ ____  ____ ___  ____  ____  _____
#   \__ \/ __/ __ `/ ___/ __/  / / / / __ `/ _ \/ __ `__ \/ __ \/ __ \/ ___/
#  ___/ / /_/ /_/ / /  / /_   / /_/ / /_/ /  __/ / / / / / /_/ / / / (__  )
# /____/\__/\__,_/_/   \__/  /_____/\__,_/\___/_/ /_/ /_/\____/_/ /_/____/
#

- name: "Start Daemons"
  tags: ["kerberos_kdc", "kerberos_kdc_start_daemons"]
  ansible.builtin.import_tasks: "start_daemons.yml"

#     ___       __    __   ____       _            _             __
#    /   | ____/ /___/ /  / __ \_____(_)___  _____(_)___  ____ _/ /____
#   / /| |/ __  / __  /  / /_/ / ___/ / __ \/ ___/ / __ \/ __ `/ / ___/
#  / ___ / /_/ / /_/ /  / ____/ /  / / / / / /__/ / /_/ / /_/ / (__  )
# /_/  |_\__,_/\__,_/  /_/   /_/  /_/_/ /_/\___/_/ .___/\__,_/_/____/
#                                               /_/

- name: "Add Principals for Service Users"
  tags: ["kerberos_kdc", "kerberos_kdc_add_principals"]
  loop: "{{ groups['cluster'] | product(services) | list }}"
  vars:
    primary: "{{ item[1].name }}"
    instance: "{{ item[0] }}"
    realm: "{{ kerberos.realm }}"
    password: "{{ kerberos.password }}"
  ansible.builtin.include_tasks:
    file: "add_principal.yml"
    apply:
      tags: ["kerberos_kdc", "kerberos_kdc_add_principals"]

- name: "Add Principals for Personal Users"
  tags: ["kerberos_kdc", "kerberos_kdc_add_principals"]
  loop: "{{ personal_users | list }}"
  vars:
    primary: "{{ item.name }}"
    realm: "{{ kerberos.realm }}"
    password: "{{ item.password }}"
  ansible.builtin.include_tasks:
    file: "add_principal.yml"
    apply:
      tags: ["kerberos_kdc", "kerberos_kdc_add_principals"]
