# Create default hdfs directories
- name: Create spark dir
  become_user: "{{ service_users.hdfs.name }}"
  loop: "{{ hdfs.spark_dirs | dict2items }}"
  shell: |
    {{ hadoop.home_path }}/bin/hdfs dfs -mkdir -p {{ item.value.path }}
  ignore_errors: true
  when:
    - inventory_hostname in groups["controllers"]

# Set Permissions
- name: Set permission for spark dir
  become_user: "{{ service_users.hdfs.name }}"
  loop: "{{ hdfs.spark_dirs | dict2items }}"
  shell: |
    {{ hadoop.home_path }}/bin/hdfs dfs -chown {{ item.value.owner }}:{{ item.value.group }} {{ item.value.path }}
    {{ hadoop.home_path }}/bin/hdfs dfs -chmod {{ item.value.mode }} {{ item.value.path }}
  ignore_errors: true
  when:
    - inventory_hostname in groups["controllers"]
