---
- name: Create Linux User
  hosts: controllers, workernodes
  become: true

  vars:
    new_user: '{{ new_user }}'

  tasks:
    - name: Add the user '{{ new_user }}'
      ansible.builtin.user:
        name: '{{ new_user }}'
        shell: /bin/bash
        create_home: true