- name: Copy Spark tarball to remote hosts
  ansible.builtin.copy:
    src: "spark/{{ spark.binaries_file }}"
    dest: "/tmp/{{ spark.binaries_file }}"

- name: Remove existing Spark directory
  ansible.builtin.file:
    path: "/opt/spark-{{ spark.version }}"
    state: absent

- name: Extract Spark tarball
  ansible.builtin.unarchive:
    src: "/tmp/{{ spark.binaries_file }}"
    dest: "/opt/"
    owner: "{{ service_users.spark.name }}"
    group: "{{ service_users.spark.group }}"
    remote_src: yes

- name: Create a symbolic link
  ansible.builtin.file:
    src: /opt/spark-{{ spark.version }}
    dest: "{{ spark.home_path }}"
    owner: "{{ service_users.spark.name }}"
    group: "{{ service_users.spark.group }}"
    state: link

- name: Copy file
  ansible.builtin.copy:
    src: "{{ spark.home_path }}/conf/spark-env.sh.template"
    dest: "{{ spark.home_path }}/conf/spark-env.sh"
    owner: "{{ service_users.spark.name }}"
    group: "{{ service_users.spark.group }}"
    remote_src: yes
  tags:
    - configuration

# Setting up environment spark-env.sh
- name: Set HADOOP_HOME in spark-env.sh
  lineinfile:
    path: "{{ spark.home_path }}/conf/spark-env.sh"
    line: "export HADOOP_HOME={{ hadoop.home_path }}"
  become: true

- name: Set HADOOP_CONF_DIR in spark-env.sh
  lineinfile:
    path: "{{ spark.home_path }}/conf/spark-env.sh"
    line: "export HADOOP_CONF_DIR=$HADOOP_HOME/etc/hadoop"
  become: true

- name: Set YARN_CONF_DIR in spark-env.sh
  lineinfile:
    path: "{{ spark.home_path }}/conf/spark-env.sh"
    line: "export YARN_CONF_DIR=$HADOOP_CONF_DIR"
  become: true

- name: Set JAVA_HOME in spark-env.sh
  lineinfile:
    path: "{{ spark.home_path }}/conf/spark-env.sh"
    line: "export JAVA_HOME={{ linux.java17_home_path }}"

# Setting up environment Variables
- name: Set Spark environment variables
  lineinfile:
    path: /etc/bash.bashrc
    line: "export SPARK_HOME={{ spark.home_path }}"
  become: true

- name: Set Spark environment variables
  lineinfile:
    path: /etc/bash.bashrc
    line: "export PATH=$PATH:$SPARK_HOME/bin"
  become: true

- name: Configure systemd Spark Master Service
  template:
    src: spark/spark-master.service.j2
    dest: /etc/systemd/system/spark-master.service
  tags:
    - configuration
  become: true
  when:
    - inventory_hostname in groups["controllers"]

- name: Enable Spark Master Service
  ansible.builtin.systemd_service:
    name: spark-master
    enabled: true
    state: stopped
    daemon_reload: true
  tags:
    - configuration
  when:
    - inventory_hostname in groups["controllers"]

- name: Configure systemd Spark Worker Service
  template:
    src: spark/spark-worker.service.j2
    dest: /etc/systemd/system/spark-worker.service
  tags:
    - configuration
  become: true
  when:
    - inventory_hostname in groups["workernodes"]

- name: Enable Spark Worker Service
  ansible.builtin.systemd_service:
    name: spark-worker
    enabled: true
    state: stopped
    daemon_reload: true
  tags:
    - configuration
  when:
    - inventory_hostname in groups["workernodes"]
