- name: Copy Spark tarball to remote hosts
  ansible.builtin.copy:
    src: "{{ filename }}"
    dest: "/tmp/spark-{{ spark_version }}-bin-hadoop3.tgz"

- name: Remove existing Spark directory
  ansible.builtin.file:
    path: "/opt/spark-{{ spark_version }}-bin-hadoop3"
    state: absent

- name: Extract Spark tarball
  ansible.builtin.unarchive:
    src: "/tmp/spark-{{ spark_version }}-bin-hadoop3.tgz"
    dest: "/opt/"
    owner: "{{ spark_user }}"
    group: "{{ spark_user }}"
    remote_src: yes

- name: Create a symbolic link
  ansible.builtin.file:
    src: /opt/spark-{{ spark_version }}-bin-hadoop3
    dest: /opt/spark
    owner: "{{ spark_user }}"
    group: "{{ spark_user }}"
    state: link

- name: Set Spark environment variables
  lineinfile:
    path: /etc/environment
    line: "export SPARK_HOME=/opt/spark"
  become: true

- name: Set Spark environment variables
  lineinfile:
    path: /etc/bash.bashrc
    line: "export PATH=$PATH:$SPARK_HOME/bin"
  become: true

- name: Configure systemd Spark Master Service
  template:
    src: spark-master.service.j2
    dest: /etc/systemd/system/spark-master.service
  tags:
    - configuration
  become: true
  when:
    - inventory_hostname in groups["controllers"]

- name: Enable Spark Master Service
  ansible.builtin.systemd_service:
    name: spark-master
    enabled: true
    state: stopped
  tags:
    - configuration
  when:
    - inventory_hostname in groups["controllers"]

- name: Configure systemd Spark Worker Service
  template:
    src: spark-worker.service.j2
    dest: /etc/systemd/system/spark-worker.service
  tags:
    - configuration
  become: true
  when:
    - inventory_hostname in groups["workernodes"]

- name: Enable Spark Worker Service
  ansible.builtin.systemd_service:
    name: spark-worker
    enabled: true
    state: stopped
  tags:
    - configuration
  when:
    - inventory_hostname in groups["workernodes"]
