- name: Start Spark Master
  ansible.builtin.service:
    name: spark-master.service
    state: started
  when:
    - inventory_hostname in groups["controllers"]

- name: Start Spark Worker
  ansible.builtin.service:
    name: spark-worker.service
    state: started
  when:
    - inventory_hostname in groups["workernodes"]
