- name: "Ensure Keytab Directory exists {{ path }}"
  ansible.builtin.file:
    path: "{{ path }}"
    state: "directory"
    mode: "0755"

- name: "Generate Keytab {{ principal }}"
  changed_when: true
  become: true
  ansible.builtin.shell: |
    kadmin.local -q "ktadd -norandkey -k {{ path }}/{{ keytab_name }} {{ principal }}"
  register: "kerberos_keytab_generate_output"
