---
- name: Install and Configure Hadoop
  hosts: controllers, workernodes
  become: true
  vars:
    hadoop_user: "hadoop"
    hadoop_version: "3.3.6"
    java_package: "openjdk-8-jdk"
    filename: "hadoop-{{ hadoop_version }}.tar.gz" 

  tasks:
  # Copy and Extract Hadoop to remote
    - name: Copy Hadoop tarball to remote hosts
      ansible.builtin.copy:
        src: "{{ filename }}"
        dest: "/tmp/{{ filename }}"

    - name: Extract Hadoop tarball
      ansible.builtin.unarchive:
        src: "/tmp/{{ filename }}"
        dest: "/opt/"
        owner: "{{ hadoop_user }}"
        group: "{{ hadoop_user }}"
        remote_src: yes

    - name: Create a symbolic link
      ansible.builtin.file:
        src: /opt/hadoop-{{ hadoop_version }}
        dest: /opt/hadoop
        owner: "{{ hadoop_user }}"
        group: "{{ hadoop_user }}"
        state: link
  
  # Setting up Directories
    - name: Create Data Directory
      ansible.builtin.file:
        path: /srv/hadoop/hdfs/data
        owner: "{{ hadoop_user }}"
        group: "{{ hadoop_user }}"
        state: directory
        mode: '0755'

    - name: Create NameNode Directory
      ansible.builtin.file:
        path: /srv/hadoop/hdfs/name
        owner: "{{ hadoop_user }}"
        group: "{{ hadoop_user }}"
        state: directory
        mode: '0755'

  # Setting up environment Variables
    - name: Set Hadoop environment variables
      lineinfile:
        path: /etc/environment
        line: 'export HADOOP_HOME=/opt/hadoop'
      become: true

    - name: Set Hadoop environment variables
      lineinfile:
        path: /etc/bash.bashrc
        line: 'export HADOOP_CONF_DIR=$HADOOP_HOME/etc/hadoop'
      become: true
    
    - name: Set Hadoop environment variables
      lineinfile:
        path: /etc/bash.bashrc
        line: 'export YARN_CONF_DIR=$HADOOP_CONF_DIR'
      become: true

    - name: Add Hadoop to PATH for all Users
      lineinfile:
        path: /etc/bash.bashrc
        line: 'export PATH=$PATH:$HADOOP_HOME/bin'
      become: true
      tags:
         - configuration

    - name: Set JAVA_HOME in hadoop-env.sh User
      lineinfile:
        path: /opt/hadoop/etc/hadoop/hadoop-env.sh
        search_string: '# export JAVA_HOME='
        line: 'export JAVA_HOME={{ java_home_path }}'
      tags:
         - configuration

  # Configuring Hadoop
    - name: Configure Hadoop core-site.xml
      template:
        src: core-site.xml.j2
        dest: /opt/hadoop/etc/hadoop/core-site.xml
        owner: "{{ hadoop_user }}"
        group: "{{ hadoop_user }}"
      tags:
         - configuration

    - name: Configure Hadoop hdfs-site.xml
      template:
        src: hdfs-site.xml.j2
        dest: /opt/hadoop/etc/hadoop/hdfs-site.xml
        owner: "{{ hadoop_user }}"
        group: "{{ hadoop_user }}"
      tags:
         - configuration

    - name: Configure Yarn yarn-site.xml
      template:
        src: yarn-site.xml.j2
        dest: /opt/hadoop/etc/hadoop/yarn-site.xml
        owner: "{{ hadoop_user }}"
        group: "{{ hadoop_user }}"
      tags:
         - configuration

    - name: Configure Hadoop mapred-site.xml
      template:
        src: mapred-site.xml.j2
        dest: /opt/hadoop/etc/hadoop/mapred-site.xml
        owner: "{{ hadoop_user }}"
        group: "{{ hadoop_user }}"
      tags:
         - configuration

  # Configuring Systemd servicesS
    - name: Configure systemd datanode service
      template:
        src: hdfs-datanode.service.j2
        dest: /etc/systemd/system/hdfs-datanode.service
      tags:
         - configuration
      become: true

    - name: Configure systemd namenode service
      template:
        src: hdfs-namenode.service.j2
        dest: /etc/systemd/system/hdfs-namenode.service
      tags:
         - configuration
      become: true

    - name: Configure systemd resourcemanager service
      template:
        src: yarn-resourcemanager.service.j2
        dest: /etc/systemd/system/yarn-resourcemanager.service
      tags:
         - configuration
      become: true

    - name: Configure systemd nodemanager service
      template:
        src: yarn-nodemanager.service.j2
        dest: /etc/systemd/system/yarn-nodemanager.service
      tags:
         - configuration
      become: true

    - name: Configure systemd historyserver service
      template:
        src: yarn-historyserver.service.j2
        dest: /etc/systemd/system/yarn-historyserver.service
      tags:
         - configuration
      become: true

  # Enable Systemd services
    - name: Enable namenode service
      ansible.builtin.systemd_service:
        name: hdfs-namenode
        enabled: true
      tags:
         - configuration
      when:
        - inventory_hostname in groups["controllers"]

    - name: Enable datanode service
      ansible.builtin.systemd_service:
        name: hdfs-datanode
        enabled: true
      tags:
         - configuration
      when:
        - inventory_hostname in groups["workernodes"]

    - name: Enable resourcemanager service
      ansible.builtin.systemd_service:
        name: yarn-resourcemanager
        enabled: true
      tags:
         - configuration
      when:
        - inventory_hostname in groups["controllers"]

    - name: Enable historyserver service
      ansible.builtin.systemd_service:
        name: yarn-historyserver
        enabled: true
      tags:
         - configuration
      when:
        - inventory_hostname in groups["controllers"]

    - name: Enable nodemanager service
      ansible.builtin.systemd_service:
        name: yarn-nodemanager
        enabled: true
      tags:
         - configuration
      when:
        - inventory_hostname in groups["workernodes"]

    - name: Add hosts to HADOOP_HOME/etc/hadoop/workers
      lineinfile:
        dest: "/opt/hadoop/etc/hadoop/workers"
        line: "{{ item }}"
      loop: "{{ groups['workernodes'] }}"
