---
- name: Stop Hadoop Services
  hosts: controllers, workernodes
  become: true

  tasks:
    - name: Stop NameNode Service
      ansible.builtin.service:
        name: hdfs-namenode.service
        state: stopped
      when:
        - inventory_hostname in groups["controllers"]
    
    - name: Stop DataNode Service
      ansible.builtin.service:
        name: hdfs-datanode.service
        state: stopped
      when:
        - inventory_hostname in groups["workernodes"]

    - name: Stop YARN ResourceManager Service
      ansible.builtin.service:
        name: yarn-resourcemanager.service
        state: stopped
      when:
        - inventory_hostname in groups["controllers"]
    
    - name: Stop YARN NodeManager Service
      ansible.builtin.service:
        name: yarn-nodemanager.service
        state: stopped
      when:
        - inventory_hostname in groups["workernodes"]
