---
- name: Start YARN
  hosts: controllers, workernodes
  become: true
  become_user: hadoop

  tasks:
    - name: Check HADOOP_HOME
      shell: echo $HADOOP_HOME
      register: hadoop_home
      failed_when: hadoop_home.stdout == ""
      tags:
         - rm
         - nm

    - name: Start Resourcemanager
      command: "$HADOOP_HOME/bin/yarn --daemon start resourcemanager"
      register: start_rm
      when:
        - inventory_hostname in groups["controllers"]
      tags:
         - rm

    - name: Display result
      debug:
        var: start_rm
      tags:
         - rm
         
    - name: Start Nodemanager
      command: "$HADOOP_HOME/bin/yarn --daemon start nodemanager"
      register: start_nm
      when:
        - inventory_hostname in groups["workernodes"]
      tags:
         - nm

    - name: Display result
      debug:
        var: start_nm
      tags:
         - nm

