---
- name: Create and Configure MySQL User
  hosts: controllers
  become: true

  tasks:
    - name: Ensure MySQL Service is started
      ansible.builtin.systemd_service:
        name: mysql.service
        state: started

    - name: Creating MySQL User
      mysql_user:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: "{{ user }}"
        password: "{{ pass }}"
        priv: '{{ db }}.{{ table }}:{{ privileges }}'
        host: '%'
        state: present