#    __  __
#   / / / /_______  __________
#  / / / / ___/ _ \/ ___/ ___/
# / /_/ (__  )  __/ /  (__  )
# \____/____/\___/_/  /____/
#

- name: "Create Service User"
  tags: ["system", "system_users"]
  loop: "{{ service_users | dict2items }}"
  vars:
    user_name: "{{ item.value.name }}"
    user_group: "{{ item.value.group }}"
    generate_ssh_key: false
  ansible.builtin.include_tasks:
    file: "create_user.yml"
    apply:
      tags: ["system", "system_users"]

- name: "Create Personal User"
  tags: ["system", "system_users"]
  loop: "{{ personal_users | selectattr('state', 'equalto', 'present') | list }}"
  vars:
    user_name: "{{ item.name }}"
    user_group: "{{ item.group }}"
    generate_ssh_key: true
  ansible.builtin.include_tasks:
    file: "create_user.yml"
    apply:
      tags: ["system", "system_users"]

- name: "Delete Personal User"
  loop: "{{ personal_users | selectattr('state', 'equalto', 'absent') | list }}"
  tags: ["system", "system_users"]
  vars:
    user_name: "{{ item.name }}"
    user_group: "{{ item.group }}"
  ansible.builtin.include_tasks:
    file: "delete_user.yml"
    apply:
      tags: ["system", "system_users"]

#     __               __          _______ __
#    / /_  ____  _____/ /______   / ____(_) /__
#   / __ \/ __ \/ ___/ __/ ___/  / /_  / / / _ \
#  / / / / /_/ (__  ) /_(__  )  / __/ / / /  __/
# /_/ /_/\____/____/\__/____/  /_/   /_/_/\___/
#

- name: "Generate /etc/hosts File"
  tags: ["system", "system_hosts_file"]
  become: true
  ansible.builtin.template:
    src: "hosts.j2"
    dest: "/etc/hosts"
    mode: "755"

- name: "Disable /etc/hosts update in /etc/cloud/cloud.cfg"
  tags: ["system", "system_hosts_file"]
  become: true
  ansible.builtin.lineinfile:
    path: "/etc/cloud/cloud.cfg"
    search_string: "- update_etc_hosts"
    line: "# - update_etc_hosts"

#        ______  __ __
#       / / __ \/ //_/
#  __  / / / / / ,<
# / /_/ / /_/ / /| |
# \____/_____/_/ |_|
#

- name: "Install JDK 8"
  tags: ["system", "system_jdk"]
  vars:
    jdk_binaries_location: "jdk/{{ ansible_facts['architecture'] }}"
    jdk_binaries_file: "{{ java.jdk_8.file }}"
    jdk_home_path: "{{ java.jdk_8.home_path }}"
  ansible.builtin.import_tasks: "install_jdk.yml"

- name: "Install JDK 17"
  tags: ["system", "system_jdk"]
  vars:
    jdk_binaries_location: "jdk/{{ ansible_facts['architecture'] }}"
    jdk_binaries_file: "{{ java.jdk_17.file }}"
    jdk_home_path: "{{ java.jdk_17.home_path }}"
  ansible.builtin.import_tasks: "install_jdk.yml"

#     ____             __
#    / __ \____ ______/ /______ _____ ____  _____
#   / /_/ / __ `/ ___/ //_/ __ `/ __ `/ _ \/ ___/
#  / ____/ /_/ / /__/ ,< / /_/ / /_/ /  __(__  )
# /_/    \__,_/\___/_/|_|\__,_/\__, /\___/____/
#                             /____/
#

- name: Update Apt Package Cache
  tags: ["system", "system_packages"]
  become: true
  ansible.builtin.apt:
    update_cache: true

- name: "Install Packages"
  tags: ["system", "system_packages"]
  become: true
  loop: "{{ apt_packages }}"
  ansible.builtin.apt:
    name: "{{ item }}"
    state: "present"
