# Copy and Extract Hadoop
- name: Copy Hadoop tarball to remote hosts
  ansible.builtin.copy:
    src: "hadoop/{{ hadoop.binaries_file }}"
    dest: "/tmp/{{ hadoop.binaries_file }}"

- name: Extract Hadoop tarball
  ansible.builtin.unarchive:
    src: "/tmp/{{ hadoop.binaries_file }}"
    dest: "/opt/"
    owner: "{{ users.hadoop.name }}"
    group: "{{ users.hadoop.group }}"
    mode: "u=rwx,g=rwx,o=r"
    remote_src: yes

- name: Create a symbolic link
  ansible.builtin.file:
    src: /opt/hadoop-{{ hadoop.version }}
    dest: /opt/hadoop
    owner: "{{ users.hadoop.name }}"
    group: "{{ users.hadoop.group }}"
    state: link

# Setting up Directories
- name: Create logs directory
  ansible.builtin.file:
    path: /opt/hadoop/logs
    owner: "{{ users.hadoop.name }}"
    group: "{{ users.hadoop.group }}"
    mode: "u=rwx,g=rwx,o=r"
    state: directory

- name: Create Data Directory
  ansible.builtin.file:
    path: /srv/hadoop/hdfs/data
    owner: "{{ users.hdfs.name }}"
    group: "{{ users.hadoop.group }}"
    state: directory
    mode: "0755"

- name: Create NameNode Directory
  ansible.builtin.file:
    path: /srv/hadoop/hdfs/name
    owner: "{{ users.hdfs.name }}"
    group: "{{ users.hadoop.group }}"
    state: directory
    mode: "0755"


# Setting up environment Variables
- name: Set HADOOP_HOME environment variable
  lineinfile:
    path: /etc/bash.bashrc
    line: "export HADOOP_HOME={{ hadoop.home_path }}"
  become: true

- name: Set HADOOP_CONF_DIR environment variable
  lineinfile:
    path: /etc/bash.bashrc
    line: "export HADOOP_CONF_DIR=$HADOOP_HOME/etc/hadoop"
  become: true

- name: Set YARN_CONF_DIR environment variable
  lineinfile:
    path: /etc/bash.bashrc
    line: "export YARN_CONF_DIR=$HADOOP_CONF_DIR"
  become: true

- name: Add Hadoop to PATH for all Users
  lineinfile:
    path: /etc/bash.bashrc
    line: "export PATH=$PATH:$HADOOP_HOME/bin"
  become: true

- name: Set JAVA_HOME in hadoop-env.sh User
  lineinfile:
    path: "{{ hadoop.home_path }}/etc/hadoop/hadoop-env.sh"
    search_string: "# export JAVA_HOME="
    line: "export JAVA_HOME={{ linux.java_home_path }}"