---
- name: Install and Configure Kafka
  hosts: controllers, workernodes
  become: true
  vars:
    kafka_user: "kafka"
    kafka_version: "2.12-3.7.0" 
    filename: "kafka_{{ kafka_version }}.tgz"

  tasks:

    - name: Copy Kafka tarball to remote hosts
      ansible.builtin.copy:
        src: "{{ filename }}"
        dest: "/tmp/{{ filename }}"

    - name: Extract Kafka tarball
      ansible.builtin.unarchive:
        src: "/tmp/{{ filename }}"
        dest: "/opt/"
        owner: "{{ kafka_user }}"
        group: "{{ kafka_user }}"
        remote_src: yes

    - name: Create a symbolic link
      ansible.builtin.file:
        src: /opt/kafka_{{ kafka_version }}
        dest: /opt/kafka
        owner: "{{ kafka_user }}"
        group: "{{ kafka_user }}"
        state: link

    - name: Create Kafka Log directory
      ansible.builtin.file:
        path: /var/log/kafka
        state: directory
        owner: "{{ kafka_user }}"
        group: "{{ kafka_user }}"

    - name: Configure Kafka
      ansible.builtin.template:
        src: server.properties.j2
        dest: /opt/kafka/config/kraft/server.properties
        owner: "{{ kafka_user }}"
        group: "{{ kafka_user }}"
      tags:
        - configuration

    - name: Format Kafka storage
      ansible.builtin.command:
        cmd: "/opt/kafka/bin/kafka-storage.sh format -t {{ kafka_cluster_id }} -c /opt/kafka/config/kraft/server.properties"
      become_user: "{{ kafka_user }}"
      become: true
      tags:
        - format

    - name: Configure systemd Kafka Broker Service
      template:
        src: kafka-broker.service.j2
        dest: /etc/systemd/system/kafka-broker.service
      tags:
         - configuration


    - name: Enable Spark Master Service
      ansible.builtin.systemd_service:
        name: kafka-broker
        enabled: true
      tags:
         - configuration

    - name: Set Kafka environment variables
      lineinfile:
        path: /etc/environment
        line: 'export KAFKA_HOME=/opt/kafka'
      become: true

    - name: Add Kafka to PATH for all Users
      lineinfile:
        path: /etc/bash.bashrc
        line: 'export PATH=$PATH:$KAFKA_HOME/bin'
      become: true
      tags:
         - configuration