---
- name: Start Kafka Cluster
  hosts: controllers, workernodes
  become: true

  tasks:
    - name: Start Broker Server
      ansible.builtin.service:
        name: kafka-broker.service
        state: stopped