  - name: Kinit
    become: true
    become_user: "{{ become_user }}"
    shell: kinit -k -t {{ keytab }} {{ principal }}
    register: keytab_output
    when:
      - inventory_hostname == groups["controllers"][0]