---
- name: Stop Standalone Spark Cluster
  hosts: controllers, workernodes
  become: true
  become_user: spark

  tasks:
    - name: Check SPARK_HOME
      shell: echo $SPARK_HOME
      register: spark_home
      failed_when: spark_home.stdout == ""

    - name: Stop Spark Master
      command: "$SPARK_HOME/sbin/stop-master.sh"
      when:
        - inventory_hostname in groups["namenodes"]

    - name: Stop Spark Worker
      command: "$SPARK_HOME/sbin/stop-worker.sh"
      when:
        - inventory_hostname in groups["workernodes"]